### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by njsh4261** [njsh4261/auth#7]
- [x] user role에 따른 페이지 상호작용 변경
 - admin일 때 모든 기능 사용 가능, normal_user는 멤버 조회만 가능
 - Token을 decode해서 user id를 읽고 DB에서 role을 조회, 권한에 따른 상호작용
- [ ] Refresh Token 추가
 - 현재는 Access Token만을 사용해서 사용자를 인증하는 구조로 되어 있음
- [ ] SMTP 관련 기능 추가
 - 이메일 인증을 통한 admin 권한 부여
  - 모든 user가 normal_user인 경우 현재는 DB에서 직접 user를 수정하는 경우에만 admin role 부여가 가능함
 - 비밀번호 초기화 (이메일을 통한)
- [ ] Auth server와 Admin API server 분할
 - 처음부터 하려 했지만 [이 문제](https://github.com/njsh4261/auth/issues/6)로 현재 서버를 통합한 상태
 - 시간 관계상 프론트 서버를 분리하여 토큰을 관리하고 HTTP request header에 첨부해 주도록 구현하는 것은 어렵고, 두 서버에 대해 token을 저장하는 쿠키를 각각 생성하는 쪽으로 고려 중임

**Comment by njsh4261** [comment]
211227 페이지 상호작용 변경 기능 구현
